%% disprecdepth: create display of recordings' depth
%% 5/16/2011 - VP

clear all
%% First getting list of recordings, location on grid, and depth

listprimdir=dir('E:\data\Recordings\Rigel\*A');
listprimdir=listprimdir(12:14);
numfiles1 = length(listprimdir);
listnames=cell(1,numfiles1);
listloc=cell(1,numfiles1);
listdepth=cell(1,numfiles1);
 for k = 1:numfiles1
     listnames{k}=listprimdir(k).name;
     filename=listnames{k};
     listloc{k}=filename(4:7);
     listdepth{k}=filename(9:13);
     rawdepth=listdepth{k};
     listdepth{k}=rawdepth(not(isletter(listdepth{k})));
 end
 convlistloc=listloc;
 convlistloc = strrep(convlistloc, 'A', '+');
 convlistloc = strrep(convlistloc, 'P', '-');
 convlistloc = strrep(convlistloc, 'L', '-');
 convlistloc = strrep(convlistloc, 'M', '+');
 
 %% Now, assuming a 15x15 grid (actually a disk), build matrix of recordings locations in depth
 
 recpos=zeros(3,numfiles1);
 
 for k = 1:numfiles1
 thisloc=char(convlistloc(k));
 recpos(1,k)=str2num(thisloc(1:2))+8; %x position, adding 8 to translate grid's center
 recpos(2,k)=str2num(thisloc(3:4))+8; %y position, adding 8 to translate grid's center
 recpos(3,k)=str2num(listdepth{k});
 end
 
%% other data
% Create outer disk
center=[8 8 0];
normal=[0 0 0];
radius=7.5;
theta=0:0.01:2*pi;
v=null(normal);
points=repmat(center',1,size(theta,2))+radius*(v(:,1)*cos(theta)+v(:,2)*sin(theta));

% create outer cylinder
[xcyl,ycyl,zcyl] = cylinder(7.5,100);
zcyl(1,:)=ones(1,101);
zcyl(2,:)=ones(1,101).*25000;
 
%% Create figure
recdepthdisp = figure('Name','Depth and location of recorded neurons',...
    'Color',[1 1 1]);

% Create axes

%subplot(1,2,1)
% Create axes
axes1=axes('ZDir','reverse',...
    'YTickLabel',{'-6','-4','-2','0','2','4','6'},...
    'XTickLabel',{'-6','-4','-2','0','2','4','6'},...
    'PlotBoxAspectRatio',[1 1 1.16666666666667],...
    'DataAspectRatio',[1 1 2142.85714285714],...
    'Color',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'CameraViewAngle',5.60116118793687);
xlim(axes1,[0 16]);
ylim(axes1,[0 16]);
view(axes1,[0 90]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create scatter3
scatter3(recpos(1,:),recpos(2,:),recpos(3,:),'MarkerFaceColor',[0 0 1],'MarkerEdgeColor',[0 0 1],...
    'Marker','.');
hold on
% plot circle
plot3(points(1,:),points(2,:),points(3,:),'LineWidth',2,...
    'Color',[0.321568638086319 0.18823529779911 0.18823529779911]);
% plot cylinder 
surf(xcyl+8,ycyl+8,zcyl,'Parent',axes1,'LineStyle','none',...
    'FaceColor',[0.952941179275513 0.87058824300766 0.733333349227905],...
    'FaceAlpha',0.3);
hold off

% Create xlabel
xlabel('mediolateral position','VerticalAlignment','cap',...
    'HorizontalAlignment','center');

% Create ylabel
ylabel('anteroposterior position','VerticalAlignment','bottom',...
    'Rotation',90,...
    'HorizontalAlignment','center');

% Create zlabel
zlabel('Depth','Visible','off','VerticalAlignment','top');

% Create title
title('top view');
% 
% axes2=subplot('Position',[0.75 0.25 0.25 0.25])
% axes('ZDir','reverse',...
%     'YTickLabel',{'-6','-4','-2','0','2','4','6'},...
%     'XTickLabel',{'-6','-4','-2','0','2','4','6'},...
%     'PlotBoxAspectRatio',[1 1 0.833333333333333],...
%     'DataAspectRatio',[1 1 2142.85714285714],...
%     'Color',[0.941176474094391 0.941176474094391 0.941176474094391],...
%     'CameraViewAngle',5.60116118793687);
%  xlim(axes2,[0 16]);
%  ylim(axes2,[0 16]);
% view(axes2,[-34.5 -10.4110419545883]);
% box(axes2,'on');
% grid(axes2,'on');
% hold(axes2,'all');
% 
% % Create scatter3
% scatter3(recpos(1,:),recpos(2,:),recpos(3,:),'MarkerFaceColor',[0 0 1],'MarkerEdgeColor',[0 0 1],...
%     'Marker','.');
% 
% hold on 
% % plot circle
% plot3(points(1,:),points(2,:),points(3,:),'LineWidth',2,...
%     'Color',[0.321568638086319 0.18823529779911 0.18823529779911]);
% % plot cylinder 
% surf(xcyl+8,ycyl+8,zcyl,'Parent',axes2,'LineStyle','none',...
%     'FaceColor',[0.952941179275513 0.87058824300766 0.733333349227905],...
%     'FaceAlpha',0.3);
% hold off
% % Create xlabel
% xlabel('mediolateral position','HorizontalAlignment','right');
% 
% % Create ylabel
% ylabel('anteroposterior position','HorizontalAlignment','left');
% 
% % Create zlabel
% zlabel('Depth');
% 
% % Create title
% % title('top view');

%% generated code
% 
% function createfigure(X1, Y1, Z1, S1, C1, X2, Y2, Z2, xdata1, ydata1, zdata1)
% %CREATEFIGURE(X1,Y1,Z1,S1,C1,X2,Y2,Z2,XDATA1,YDATA1,ZDATA1)
% %  X1:  scatter3 x
% %  Y1:  scatter3 y
% %  Z1:  scatter3 z
% %  S1:  scatter3 s
% %  C1:  scatter3 c
% %  X2:  vector of x data
% %  Y2:  vector of y data
% %  Z2:  vector of z data
% %  XDATA1:  surface xdata
% %  YDATA1:  surface ydata
% %  ZDATA1:  surface zdata
% 
% %  Auto-generated by MATLAB on 16-May-2011 21:15:42
% 
% % Create figure
% figure1 = figure('Renderer','OpenGL',...
%     'Name','Depth and location of recorded neurons',...
%     'Color',[1 1 1]);
% 
% % Create subplot
% subplot1 = subplot(2,2,1,'Parent',figure1,'ZDir','reverse',...
%     'YTickLabel',{'','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
%     'YTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
%     'YMinorTick','on',...
%     'XTickLabel',{'','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
%     'XTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
%     'PlotBoxAspectRatio',[1 1 1.16666666666667],...
%     'DataAspectRatio',[1 1 2142.85714285714],...
%     'Color',[0.941176474094391 0.941176474094391 0.941176474094391],...
%     'CameraViewAngle',5.60116118793687);
% % Uncomment the following line to preserve the X-limits of the axes
% % xlim(subplot1,[0 16]);
% % Uncomment the following line to preserve the Y-limits of the axes
% % ylim(subplot1,[0 16]);
% box(subplot1,'on');
% grid(subplot1,'on');
% hold(subplot1,'all');
% 
% % Create scatter3
% scatter3(X1,Y1,Z1,S1,C1,...
%     'MarkerFaceColor',[0.321568638086319 0.18823529779911 0.18823529779911],...
%     'MarkerEdgeColor',[0.34901961684227 0.200000002980232 0.329411774873734],...
%     'Parent',subplot1);
% 
% % Create plot3
% plot3(X2,Y2,Z2,'Parent',subplot1,'LineWidth',2,...
%     'Color',[0.321568638086319 0.18823529779911 0.18823529779911]);
% 
% % Create surf
% surf(xdata1,ydata1,zdata1,'Parent',subplot1,'LineStyle','none',...
%     'FaceColor',[0.952941179275513 0.87058824300766 0.733333349227905],...
%     'FaceAlpha',0.3);
% 
% % Create xlabel
% xlabel('lateromedial','FontName','Tahoma');
% 
% % Create ylabel
% ylabel('anteroposterior','FontName','Tahoma');
% 
% % Create zlabel
% zlabel('Depth','Visible','off','VerticalAlignment','top');
% 
% % Create title
% title('top view','FontWeight','demi','FontName','Tahoma');
% 
% % Create axes
% axes1 = axes('Parent',figure1,'ZDir','reverse',...
%     'YTickLabel',{'','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
%     'YTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
%     'YMinorTick','on',...
%     'XTickLabel',{'','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
%     'XTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
%     'Position',[0.546595380667234 0.608327005220698 0.334659090909091 0.341162790697675],...
%     'PlotBoxAspectRatio',[1 1 0.729166666666668],...
%     'DataAspectRatio',[1 1 2142.85714285714],...
%     'Color',[0.941176474094391 0.941176474094391 0.941176474094391],...
%     'CameraViewAngle',5.60116118793687);
% % Uncomment the following line to preserve the X-limits of the axes
% % xlim(axes1,[0 16]);
% % Uncomment the following line to preserve the Y-limits of the axes
% % ylim(axes1,[0 16]);
% view(axes1,[-90 0]);
% box(axes1,'on');
% grid(axes1,'on');
% hold(axes1,'all');
% 
% % Create scatter3
% scatter3(X1,Y1,Z1,S1,C1,...
%     'MarkerFaceColor',[0.321568638086319 0.18823529779911 0.18823529779911],...
%     'MarkerEdgeColor',[0.34901961684227 0.200000002980232 0.329411774873734],...
%     'Parent',axes1);
% 
% % Create plot3
% plot3(X2,Y2,Z2,'Parent',axes1,'LineWidth',2,...
%     'Color',[0.321568638086319 0.18823529779911 0.18823529779911]);
% 
% % Create surf
% surf(xdata1,ydata1,zdata1,'Parent',axes1,'LineStyle','none',...
%     'FaceColor',[0.952941179275513 0.87058824300766 0.733333349227905],...
%     'FaceAlpha',0.3);
% 
% % Create xlabel
% xlabel('lateromedial','Visible','off','HorizontalAlignment','center',...
%     'FontName','Tahoma');
% 
% % Create ylabel
% ylabel('anteroposterior','VerticalAlignment','cap',...
%     'HorizontalAlignment','center',...
%     'FontName','Tahoma');
% 
% % Create zlabel
% zlabel('Depth (mm)','VerticalAlignment','top');
% 
% % Create title
% title('anteroposterior profile','FontWeight','demi','FontName','Tahoma');
% 
% % Create axes
% axes2 = axes('Parent',figure1,'ZDir','reverse',...
%     'YTickLabel',{'','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
%     'YTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
%     'YMinorTick','on',...
%     'XTickLabel',{'','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
%     'XTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
%     'Position',[0.129144568006843 0.0613882297104895 0.334659090909091 0.341162790697675],...
%     'PlotBoxAspectRatio',[1 1 0.729166666666668],...
%     'DataAspectRatio',[1 1 2142.85714285714],...
%     'Color',[0.941176474094391 0.941176474094391 0.941176474094391],...
%     'CameraViewAngle',5.60116118793687);
% % Uncomment the following line to preserve the X-limits of the axes
% % xlim(axes2,[0 16]);
% % Uncomment the following line to preserve the Y-limits of the axes
% % ylim(axes2,[0 16]);
% view(axes2,[0 0]);
% box(axes2,'on');
% grid(axes2,'on');
% hold(axes2,'all');
% 
% % Create scatter3
% scatter3(X1,Y1,Z1,S1,C1,...
%     'MarkerFaceColor',[0.321568638086319 0.18823529779911 0.18823529779911],...
%     'MarkerEdgeColor',[0.34901961684227 0.200000002980232 0.329411774873734],...
%     'Parent',axes2);
% 
% % Create plot3
% plot3(X2,Y2,Z2,'Parent',axes2,'LineWidth',2,...
%     'Color',[0.321568638086319 0.18823529779911 0.18823529779911]);
% 
% % Create surf
% surf(xdata1,ydata1,zdata1,'Parent',axes2,'LineStyle','none',...
%     'FaceColor',[0.952941179275513 0.87058824300766 0.733333349227905],...
%     'FaceAlpha',0.3);
% 
% % Create xlabel
% xlabel('lateromedial','VerticalAlignment','cap',...
%     'HorizontalAlignment','center',...
%     'FontName','Tahoma');
% 
% % Create ylabel
% ylabel('anteroposterior','Visible','off','HorizontalAlignment','center',...
%     'FontName','Tahoma');
% 
% % Create zlabel
% zlabel('Depth (mm)','VerticalAlignment','top');
% 
% % Create title
% title('lateromedial profile','FontWeight','demi','FontName','Tahoma');
% 
% % Create axes
% axes3 = axes('Parent',figure1,'ZDir','reverse',...
%     'YTickLabel',{'','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
%     'YTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
%     'YMinorTick','on',...
%     'XTickLabel',{'','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
%     'XTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
%     'Position',[0.584260051325919 0.146938775510204 0.285714285714286 0.220408163265306],...
%     'PlotBoxAspectRatio',[1 1 0.875000000000001],...
%     'DataAspectRatio',[1 1 2142.85714285714],...
%     'Color',[0.941176474094391 0.941176474094391 0.941176474094391],...
%     'CameraViewAngle',5.60116118793687);
% % Uncomment the following line to preserve the X-limits of the axes
% % xlim(axes3,[0 16]);
% % Uncomment the following line to preserve the Y-limits of the axes
% % ylim(axes3,[0 16]);
% view(axes3,[-20 36]);
% box(axes3,'on');
% grid(axes3,'on');
% hold(axes3,'all');
% 
% % Create scatter3
% scatter3(X1,Y1,Z1,S1,C1,...
%     'MarkerFaceColor',[0.321568638086319 0.18823529779911 0.18823529779911],...
%     'MarkerEdgeColor',[0.34901961684227 0.200000002980232 0.329411774873734],...
%     'Parent',axes3);
% 
% % Create plot3
% plot3(X2,Y2,Z2,'Parent',axes3,'LineWidth',2,...
%     'Color',[0.321568638086319 0.18823529779911 0.18823529779911]);
% 
% % Create surf
% surf(xdata1,ydata1,zdata1,'Parent',axes3,'LineStyle','none',...
%     'FaceColor',[0.952941179275513 0.87058824300766 0.733333349227905],...
%     'FaceAlpha',0.3);
% 
% % Create zlabel
% zlabel('Depth (mm)','VerticalAlignment','top');
% end
