function createfigure
%CREATEFIGURE

%  Auto-generated by MATLAB on 10-Dec-2012 12:35:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Position',[0 0 1 1]);

% Create hggroup
hggroup1 = hggroup('Parent',axes1);

% Create rectangle
rectangle('Parent',hggroup1,'Position',[75 75 50 50],'LineWidth',3,...
    'EdgeColor',[1 1 1],...
    'Curvature',[1 1]);

% Create rectangle
rectangle('Parent',hggroup1,'Position',[75 75 50 50],'LineWidth',2,...
    'EdgeColor',[0 0 1],...
    'Curvature',[1 1]);

% Create hggroup
hggroup2 = hggroup('Parent',axes1);

% Create rectangle
rectangle('Parent',hggroup2,'Position',[50 50 100 100],'LineWidth',3,...
    'EdgeColor',[1 1 1],...
    'Curvature',[1 1]);

% Create rectangle
rectangle('Parent',hggroup2,'Position',[50 50 100 100],'LineWidth',2,...
    'EdgeColor',[0 0 1],...
    'Curvature',[1 1]);

% Create hggroup
hggroup3 = hggroup('Parent',axes1);

% Create rectangle
rectangle('Parent',hggroup3,'Position',[25 25 150 150],'LineWidth',3,...
    'EdgeColor',[1 1 1],...
    'Curvature',[1 1]);

% Create rectangle
rectangle('Parent',hggroup3,'Position',[25 25 150 150],'LineWidth',2,...
    'EdgeColor',[0 0 1],...
    'Curvature',[1 1]);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.527525357740516 0.623781856983793 0.128410914927769 0.097323600973236]);
box(axes2,'on');

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.702305932174448 0.717439069652355 0.128410914927769 0.097323600973236]);
box(axes3,'on');

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.0477688603531302 0.811738061363355 0.128410914927769 0.097323600973236]);
box(axes4,'on');

% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.516306478603874 0.475062283496226 0.128410914927769 0.097323600973236]);
box(axes5,'on');

% Create axes
axes6 = axes('Parent',figure1,...
    'Position',[0.685861821659097 0.475062283496226 0.128410914927769 0.097323600973236]);
box(axes6,'on');

% Create axes
axes7 = axes('Parent',figure1,...
    'Position',[0.85541716471432 0.475062283496226 0.128410914927769 0.097323600973236]);
box(axes7,'on');

% Create axes
axes8 = axes('Parent',figure1,...
    'Position',[0.527525357740516 0.314204657924039 0.128410914927769 0.097323600973236]);
box(axes8,'on');

% Create axes
axes9 = axes('Parent',figure1,...
    'Position',[0.700700795737851 0.218401738216009 0.128410914927769 0.097323600973236]);
box(axes9,'on');

% Create axes
axes10 = axes('Parent',figure1,...
    'Position',[0.851762917933132 0.0827737226277372 0.128410914927769 0.097323600973236]);
box(axes10,'on');

% Create axes
axes11 = axes('Parent',figure1,...
    'Position',[0.315468050954545 0.623781856983793 0.128410914927769 0.097323600973236]);
box(axes11,'on');

% Create axes
axes12 = axes('Parent',figure1,...
    'Position',[0.162356818414672 0.689204657924039 0.128410914927769 0.097323600973236]);
box(axes12,'on');

% Create axes
axes13 = axes('Parent',figure1,...
    'Position',[0.851762917933132 0.811738061363355 0.128410914927769 0.097323600973236]);
box(axes13,'on');

% Create axes
axes14 = axes('Parent',figure1,...
    'Position',[0.346751135548649 0.475062283496226 0.128410914927769 0.097323600973236]);
box(axes14,'on');

% Create axes
axes15 = axes('Parent',figure1,...
    'Position',[0.177195792493426 0.475062283496226 0.128410914927769 0.097323600973236]);
box(axes15,'on');

% Create axes
axes16 = axes('Parent',figure1,...
    'Position',[0.00764044943820231 0.475062283496226 0.128410914927769 0.097323600973236]);
box(axes16,'on');

% Create axes
axes17 = axes('Parent',figure1,...
    'Position',[0.315468050954545 0.314204657924039 0.128410914927769 0.097323600973236]);
box(axes17,'on');

% Create axes
axes18 = axes('Parent',figure1,...
    'Position',[0.160751681978075 0.223876190770753 0.128410914927769 0.097323600973236]);
box(axes18,'on');

% Create axes
axes19 = axes('Parent',figure1,...
    'Position',[0.0477688603531302 0.0827737226277372 0.128410914927769 0.097323600973236]);
box(axes19,'on');

